// <auto-generated />
using CatalogoBolo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogoBolo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240719114714_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogoBolo.Data.Bolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Bolos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Bolo1",
                            ImagemUrl = "https://img.freepik.com/fotos-premium/bolo-de-milho-delicioso-na-mesa_434193-2483.jpg?w=1060",
                            Nome = "Bolo de Banana",
                            Preco = 10000m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Bolo2",
                            ImagemUrl = "https://images.pexels.com/photos/960540/pexels-photo-960540.jpeg?auto=compress&cs=tinysrgb&w=600",
                            Nome = "Bolo brigadeiro",
                            Preco = 100500m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Bolo3",
                            ImagemUrl = "https://img.freepik.com/fotos-gratis/bolo-de-frutas-de-sobremesa_144627-10487.jpg?w=1060&t=st=1721384999~exp=1721385599~hmac=e86fa13fd41adbc30fd24558ac3907eb89198d5d6916d7dbb8833ab52e183fdc",
                            Nome = "Bolo de chocolate",
                            Preco = 12750m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Bolo4",
                            ImagemUrl = "https://img.freepik.com/fotos-gratis/femea-servindo-um-delicioso-bolo-de-cidra-com-esmalte-em-cima-de-uma-mesa-branca_181624-58169.jpg?w=360&t=st=1721385148~exp=1721385748~hmac=5fd040000ce347c207d1e0b38b908d8ed67f34bd9b732fb83aa88425022a6a53",
                            Nome = "Bolo de laranja",
                            Preco = 9500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
